### ISSUE TITLE
Figure out how to get the model to store multiple pictures for each form

### ISSUE THREAD

**Issue by betsymariecarter** [Capstone-Project-Team-ToDomagotchi/todomagotchi#60]
- [ ] How do we get the component to switch over to the next picture based on the number of experience points?
- [x] How do we store these multiple pictures in the same box for the creature's image?

**Comment by sstephens0907** [comment]
- db needs to track how many exp point User has
- will use a ternary to swap the images based on the stage, something like below:
```javascript
let plantImage = '';

plantImage = currentStage === 1 ? 'image1.jpg' :
              currentStage === 2 ? 'image2.jpg' :
              currentStage === 3 ? 'image3.jpg' :
              'defaultImage.jpg';

<img src={plantImage} alt="Plant image" />
```
